---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	load_context(load_context)
	classify_intent(classify_intent)
	agent(agent)
	agent_tools(agent_tools)
	agent_approve(agent_approve)
	agent_execute(agent_execute)
	pm_call(pm_call)
	pm_await(pm_await)
	pm_reply(pm_reply)
	pm_error(pm_error)
	save_reply(save_reply)
	__end__([<p>__end__</p>]):::last
	__start__ --> load_context;
	agent -.-> agent_tools;
	agent -.-> save_reply;
	agent_approve --> agent_execute;
	agent_execute -.-> agent;
	agent_execute -.-> pm_call;
	agent_execute -.-> save_reply;
	agent_tools -.-> agent;
	agent_tools -.-> agent_approve;
	classify_intent -.-> agent;
	classify_intent -.-> pm_call;
	load_context --> classify_intent;
	pm_await --> pm_call;
	pm_call -.-> pm_await;
	pm_call -.-> pm_error;
	pm_call -.-> pm_reply;
	pm_call -.-> save_reply;
	pm_error -.-> pm_call;
	pm_error -.-> save_reply;
	pm_reply --> save_reply;
	save_reply --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
